### PR TITLE
Update ruby version matrix to include current ruby versions

### PR DESCRIPTION
**Pull request by kieranj**
Ruby 2.6 was EOL as of 31/03/22 and ruby 3.0/3.1 have been widely adopted by the community so its important to run the test suite against these versions

### CODE REVIEW

**Comment by gregjoy1** [comment]
Adding weight to this, Bookwhen upgraded to Ruby 3 recently and have found that the [OpenActive dataset-site-template-ruby gem](https://github.com/openactive/dataset-site-template-ruby) (that relies on this gem as a dependency) [is broken](https://data.bookwhen.com/).

Once this is resolved, we will upgrade to the latest version to resolve it. Unfortunately we are super busy at the moment and don't have the resources to investigate further.

```

ArgumentError: missing keyword: :field
  from openactive (0.1.2) lib/openactive/concerns/json_ld_serializable.rb:28:in `block in values'
  from openactive (0.1.2) lib/openactive/concerns/json_ld_serializable.rb:28:in `each'
  from openactive (0.1.2) lib/openactive/concerns/json_ld_serializable.rb:28:in `values'
  from openactive (0.1.2) lib/openactive/helpers/json_ld.rb:23:in `prepare_data_for_serialization'
  from openactive (0.1.2) lib/openactive/helpers/json_ld.rb:84:in `serialize_value'
  from openactive-dataset_site (0.1.1) lib/openactive/dataset_site/template_renderer.rb:29:in `method_missing'
  from mustache (1.1.1) lib/mustache/context.rb:148:in `call'
  from mustache (1.1.1) lib/mustache/context.rb:148:in `find'
  from mustache (1.1.1) lib/mustache/context.rb:116:in `block in fetch'
  from mustache (1.1.1) lib/mustache/context.rb:112:in `each'
  from mustache (1.1.1) lib/mustache/context.rb:112:in `fetch'
  from mustache (1.1.1) lib/mustache/context.rb:94:in `[]'
  from mustache (1.1.1) lib/mustache/template.rb:116:in `render'
  from mustache (1.1.1) lib/mustache/template.rb:44:in `render'
  from mustache (1.1.1) lib/mustache.rb:133:in `render'
  from app/classes/api/openactive/data_site/template_renderer.rb:9:in `render_data_site'
  ...
```

**Comment by nickevansuk** [comment]
@gregjoy1 thanks for reporting this - I've just upgraded both to Ruby 3 (see https://github.com/openactive/dataset-site-template-ruby/pull/22), so hopefully it'll be easy to get your dataset site up-and-runnning again!

**Comment by gregjoy1** [comment]
Hi @nickevansuk, massive thanks for this! 🙂 We have hit upon a snag [where the `activesupport` dependency for this gem is pinned to version `6.1`](https://github.com/openactive/models-ruby/pull/39/files#diff-09c3b31154b15855b4a7fcf24ccde63081e09142c18c742f0206a0ff47daca48R32) and we are using version `7.1`. Unfortunately this blocks the installation of the updated version of this gem as version `6.1` and `7.1` cannot co-exist within the same runtime.

FYI @kieranj 

We are quite tight for time or else I would have forked it and resolved it myself. I know you are super busy but when you get a spare moment, please may you remove that pin so that we are able to use this with modern Rails 🙂 

Also the latest version of the [`openactive-dataset_site` Gem](https://github.com/openactive/dataset-site-template-ruby) has not been pushed to Ruby gems yet (easy thing to miss), if its a quick job - may you push it or else we can explicitly specify the use of the Github repo with the latest commit. 🙂

**Comment by nickevansuk** [comment]
Thanks @gregjoy1  - would this PR resolve this per your understanding? https://github.com/openactive/models-ruby/pull/46

`openactive-dataset_site` doesn't have a version of this library pinned, so it should just use the latest version? (the latest commit in that repo is just an update to CI).

I'm not a Rails developer, so do let me know if I'm misunderstanding anything here!

**Pull request merged**
